### ISSUE TITLE
Infinite loop in Client transaction due to "Watched variable changed"

### ISSUE THREAD

**Issue by mattrunchey** [andymccurdy/redis-py#1279]
**Version**: `redis` 4.0, `redis-py` newest 3.4.11

**Platform**: Any supported platform and python combo. Observed on `python:3.7-slim` and OSX

**Description**: 

On 3.3.11, our tests ran fine. On 3.4.10/11, everything hangs due to getting infinitely stuck in the [WatchError](https://github.com/andymccurdy/redis-py/blob/1b050753d6ec6a6630c2cfd83c2cfbd741a3ced3/redis/client.py#L784) for a transaction.

I am not the most familiar with using `redis` and am still trying to pinpoint what we're doing wrong, and how to communicate an example of recreating that doesn't rely on a bunch of our surrounding code. I intend to update this ticket when I do find something, though.

In the meantime, I've been trying to see which changes in the last 28 commits since 3.3.11 could be affecting this. I didn't notice any obvious changes in the release notes, nor in the functions that we seem to be calling. 

Does anyone know a possible fruitful place to look for finding out how this is happening?

EDIT -- how to recreate.

I simply created a standalone pytest file, and ran a local `redis` container using an upstream container.

`docker-compose.yml`
```
version: "2.1"

services:

  redis:
    restart: always
    image: redis:4.0
    command: ["redis-server", "--port", "${REDIS_PORT:-6379}","--appendonly", "yes"]
    expose:
      - "${REDIS_PORT:-6379}"
    ports:
      - "${REDIS_PORT:-6379}:${REDIS_PORT:-6379}"
    volumes:
      - data-redis:/data


volumes:
  data-redis:
```

Then, alongside it, I created a file named `scratch.py`:

```python
import redis
import json

import pytest

LOCAL_FORWARD = "alias:local-labels"
FORWARD_CACHE = "alias:label-to-device"
REVERSE_CACHE = "alias:device-to-label"

def _add_local(pipe):
    print("lookup")

    alias = "alias--1"
    json_data = json.dumps({"version": "v1", "alias": "alias--1", "target": "d--abcd-0000-0000-0000", "description": "a test"})
    target = "d--abcd-0000-0000-0000"
    reverse = ['alias--1']

    pipe.hset(LOCAL_FORWARD, alias, json_data)

    pipe.hset(FORWARD_CACHE, alias, target)
    pipe.hset(REVERSE_CACHE, target, json.dumps(reverse))



def test_this_on_for_size():

    client = redis.Redis()
    client.transaction(_add_local, LOCAL_FORWARD, REVERSE_CACHE, FORWARD_CACHE)
```

How to run/recreate (commands run from directory with the two files above present):

```shell
docker-compose up -d
pip install json
pip install redis==3.3.11
pytest scratch.py 
<test will pass almost instantly>
pip install redis==3.4.1
pytest scratch.py
<test will hang>
pip install redis==3.3.11
pytest scratch.py
<test will pass almost instantly>
<repeat if you want to, same results>
```
